apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
  namespace: {{ .Values.namespace }}
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.serviceName }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080