version: '3.8'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: prakt7
    ports:
      - "5438:5432"

  app:
    build: .
    ports:
      - "8085:8080"
    depends_on:
      - db